// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package haxsh

import reflect "reflect"
import util "yo/util"
import q "yo/db/query"

type _ = q.F // just in case of no other generated import users
type apiPkgInfo util.Void

func (apiPkgInfo) PkgName() string    { return "main" }
func (me apiPkgInfo) PkgPath() string { return reflect.TypeOf(me).PkgPath() }

var PkgInfo = apiPkgInfo{}

const Err___yo_authLogin_AccountDoesNotExist util.Err = "___yo_authLogin_AccountDoesNotExist"
const Err___yo_authLogin_EmailInvalid util.Err = "___yo_authLogin_EmailInvalid"
const Err___yo_authLogin_EmailRequiredButMissing util.Err = "___yo_authLogin_EmailRequiredButMissing"
const Err___yo_authLogin_OkButFailedToCreateSignedToken util.Err = "___yo_authLogin_OkButFailedToCreateSignedToken"
const Err___yo_authLogin_WrongPassword util.Err = "___yo_authLogin_WrongPassword"
const Err___yo_authRegister_EmailAddrAlreadyExists util.Err = "___yo_authRegister_EmailAddrAlreadyExists"
const Err___yo_authRegister_EmailInvalid util.Err = "___yo_authRegister_EmailInvalid"
const Err___yo_authRegister_EmailRequiredButMissing util.Err = "___yo_authRegister_EmailRequiredButMissing"
const Err___yo_authRegister_PasswordInvalid util.Err = "___yo_authRegister_PasswordInvalid"
const Err___yo_authRegister_PasswordTooLong util.Err = "___yo_authRegister_PasswordTooLong"
const Err___yo_authRegister_PasswordTooShort util.Err = "___yo_authRegister_PasswordTooShort"
const ErrDbUpdate_ExpectedChangesForUpdate util.Err = "DbUpdate_ExpectedChangesForUpdate"
const ErrDbUpdate_ExpectedQueryForUpdate util.Err = "DbUpdate_ExpectedQueryForUpdate"
const UserSignInEmailAddr = q.F("EmailAddr")
const UserSignInPasswordPlain = q.F("PasswordPlain")
const UserSignUpEmailAddr = q.F("EmailAddr")
const UserSignUpPasswordPlain = q.F("PasswordPlain")
const UserUpdateChanges = q.F("Changes")
const UserUpdateId = q.F("Id")
const UserUpdateIncludingEmptyOrMissingFields = q.F("IncludingEmptyOrMissingFields")
